### ISSUE TITLE
Error while loading Gligen

### ISSUE THREAD

**Issue by wasphulud** [Sierkinhane/VisorGPT#7]
Hello,

While loading GLigen, I have got the following errors. Are those the right weights please?
```Traceback (most recent call last):
  File "gradio_demo.py", line 35, in <module>
    g_config, g_grounding_tokenizer_input = build_gligen_model(ckpt=gligen_model_path)
  File "/home/VisorGPT/demo/GLIGEN/gligen/gligen_inference_box.py", line 229, in build_gligen_model
    model, autoencoder, text_encoder, diffusion, config = load_ckpt(ckpt)
  File "/home/VisorGPT/demo/GLIGEN/gligen/gligen_inference_box.py", line 99, in load_ckpt
    text_encoder.load_state_dict( saved_ckpt["text_encoder"]  )
  File "/opt/conda/envs/visorgpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for FrozenCLIPEmbedder:
        Unexpected key(s) in state_dict: "transformer.text_model.embeddings.position_ids".

**Comment by Sierkinhane** [comment]
Hi, what's the version of transformers? You can try to use transformers==4.27.4.

**Comment by wasphulud** [comment]
I got multiple errors while "pip install -r requirements.txt"(especially when there is editable install with /tmp/ ...)  so I deleted the relevant lines and installed them manually.

I was able to load the model, but getting errors in gradio this time

```Traceback (most recent call last):
  File "/opt/conda/envs/visorgpt/lib/python3.8/site-packages/gradio/routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "/opt/conda/envs/visorgpt/lib/python3.8/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/visorgpt/lib/python3.8/site-packages/gradio/blocks.py", line 1559, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/opt/conda/envs/visorgpt/lib/python3.8/site-packages/gradio/blocks.py", line 1435, in postprocess_data
    state[output_id] = self.blocks[output_id].__class__(**args)
  File "/opt/conda/envs/visorgpt/lib/python3.8/site-packages/gradio/blocks.py", line 115, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'render'

**Comment by Sierkinhane** [comment]
Please try to install gradio==3.25.0 gradio-client==0.0.10

**Comment by wasphulud** [comment]
I had some other versions discrepancies too: I have reinstalled all required versions and it's working like a charm now.

Thank you @Sierkinhane

**Comment by Sierkinhane** [comment]
Thank you for your interest! Btw, welcome to star our project :)
